/**
 * KKTC Thematic Travel Routes
 * Curated multi-day travel experiences for exploring North Cyprus
 * 
 * Note: This is informational content only - no pricing
 */

import { ThematicRoute } from '@/types';
import i18n from '@/lib/i18n';

/**
 * Featured thematic routes for the Explore screen
 */
export const featuredRoutes: ThematicRoute[] = [
  {
    id: 'route-1',
    slug: '3-gunluk-girne-tarihi-turu',
    title: '3 Günlük Girne Tarihi Turu',
    subtitle: 'Girne\'nin tarihi dokusunu keşfedin',
    theme: 'history',
    baseLocation: 'Girne',
    region: 'Kuzey Kıbrıs',
    durationDays: 3,
    durationLabel: '3 Gün 2 Gece',
    coverImage: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&h=600&fit=crop',
    tags: ['Tarihi', 'Girne', 'Kültür', 'Aile'],
    highlighted: true,
    difficulty: 'easy',
    bestSeason: 'İlkbahar - Sonbahar',
    totalStops: 9,
    itinerary: [
      {
        dayIndex: 1,
        title: 'Girne Kalesi ve Liman',
        description: 'İlk gün Girne\'nin kalbinde tarihi keşif',
        stops: [
          {
            id: 'stop-1-1',
            order: 1,
            type: 'tour',
            name: 'Girne Kalesi',
            description: 'Bizans döneminden kalma muhteşem kale ve batık gemi müzesi',
            timeOfDay: 'morning',
            duration: '2-3 saat',
            latitude: 35.3420,
            longitude: 33.3183,
            image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400&h=300&fit=crop',
            tips: 'Sabah erken saatlerde daha az kalabalık olur',
          },
          {
            id: 'stop-1-2',
            order: 2,
            type: 'restaurant',
            name: 'Girne Limanı Restoranları',
            description: 'Tarihi limanda deniz manzaralı öğle yemeği',
            timeOfDay: 'noon',
            duration: '1-1.5 saat',
            latitude: 35.3415,
            longitude: 33.3190,
          },
          {
            id: 'stop-1-3',
            order: 3,
            type: 'poi',
            name: 'Girne Eski Şehir',
            description: 'Dar sokaklar, butik dükkanlar ve tarihi yapılar',
            timeOfDay: 'afternoon',
            duration: '2 saat',
            latitude: 35.3410,
            longitude: 33.3175,
            tips: 'Rahat yürüyüş ayakkabısı giyin',
          },
        ],
      },
      {
        dayIndex: 2,
        title: 'Bellapais ve St. Hilarion',
        description: 'Dağlardaki tarihi hazineler',
        stops: [
          {
            id: 'stop-2-1',
            order: 1,
            type: 'tour',
            name: 'Bellapais Manastırı',
            description: '13. yüzyıldan kalma gotik mimari harikası',
            timeOfDay: 'morning',
            duration: '2 saat',
            latitude: 35.3080,
            longitude: 33.3540,
            image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
            tips: 'Gün batımı manzarası muhteşemdir',
          },
          {
            id: 'stop-2-2',
            order: 2,
            type: 'cafe',
            name: 'Bellapais Köyü',
            description: 'Köy kahvesinde mola ve yerel lezzetler',
            timeOfDay: 'noon',
            duration: '1 saat',
            latitude: 35.3075,
            longitude: 33.3535,
          },
          {
            id: 'stop-2-3',
            order: 3,
            type: 'tour',
            name: 'St. Hilarion Kalesi',
            description: 'Beşparmak Dağları\'ndaki masalsı kale',
            timeOfDay: 'afternoon',
            duration: '2-3 saat',
            latitude: 35.3115,
            longitude: 33.2815,
            image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=300&fit=crop',
            tips: 'Yürüyüş için su ve şapka getirin',
          },
        ],
      },
      {
        dayIndex: 3,
        title: 'Antik Kentler',
        description: 'Roma ve Helenistik dönem kalıntıları',
        stops: [
          {
            id: 'stop-3-1',
            order: 1,
            type: 'tour',
            name: 'Salamis Antik Kenti',
            description: 'Antik dönemin en önemli liman şehirlerinden biri',
            timeOfDay: 'morning',
            duration: '3 saat',
            latitude: 35.1850,
            longitude: 33.9020,
            image: 'https://images.unsplash.com/photo-1553913861-c0a9e9d5c5e9?w=400&h=300&fit=crop',
            tips: 'Geniş alan, rahat ayakkabı şart',
          },
          {
            id: 'stop-3-2',
            order: 2,
            type: 'poi',
            name: 'Gazimağusa Surları',
            description: 'Venedik döneminden kalma etkileyici surlar',
            timeOfDay: 'afternoon',
            duration: '2 saat',
            latitude: 35.1250,
            longitude: 33.9410,
          },
          {
            id: 'stop-3-3',
            order: 3,
            type: 'poi',
            name: 'Lala Mustafa Paşa Camii',
            description: 'Gotik mimari örneği, eski St. Nicholas Katedrali',
            timeOfDay: 'afternoon',
            duration: '1 saat',
            latitude: 35.1245,
            longitude: 33.9405,
          },
        ],
      },
    ],
  },
  {
    id: 'route-2',
    slug: 'lefkosa-sokak-lezzetleri',
    title: 'Lefkoşa Sokak Lezzetleri',
    subtitle: 'Başkentin gastronomi rotası',
    theme: 'food',
    baseLocation: 'Lefkoşa',
    region: 'Kuzey Kıbrıs',
    durationDays: 1,
    durationLabel: 'Tam Gün',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop',
    tags: ['Yeme-İçme', 'Lefkoşa', 'Sokak Lezzetleri'],
    highlighted: true,
    difficulty: 'easy',
    bestSeason: 'Tüm Yıl',
    totalStops: 6,
    itinerary: [
      {
        dayIndex: 1,
        title: 'Lefkoşa Lezzet Turu',
        description: 'Sabahtan akşama kadar yerel tatlar',
        stops: [
          {
            id: 'stop-lef-1',
            order: 1,
            type: 'cafe',
            name: 'Bandabulya (Kapalı Çarşı)',
            description: 'Geleneksel Kıbrıs kahvaltısı ve taze sıkılmış portakal suyu',
            timeOfDay: 'morning',
            duration: '1 saat',
            latitude: 35.1753,
            longitude: 33.3642,
            tips: 'Hellim ve zeytinyağlı kahvaltıyı deneyin',
          },
          {
            id: 'stop-lef-2',
            order: 2,
            type: 'poi',
            name: 'Arasta Sokağı',
            description: 'Tarihi çarşıda yürüyüş ve yerel ürünler',
            timeOfDay: 'morning',
            duration: '1.5 saat',
            latitude: 35.1748,
            longitude: 33.3638,
          },
          {
            id: 'stop-lef-3',
            order: 3,
            type: 'restaurant',
            name: 'Büyük Han',
            description: 'Osmanlı döneminden kalma handa öğle yemeği',
            timeOfDay: 'noon',
            duration: '1.5 saat',
            latitude: 35.1760,
            longitude: 33.3635,
            image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
            tips: 'Molehiya veya şeftali kebabı deneyin',
          },
          {
            id: 'stop-lef-4',
            order: 4,
            type: 'cafe',
            name: 'Selimiye Meydanı',
            description: 'Türk kahvesi ve tatlı molası',
            timeOfDay: 'afternoon',
            duration: '45 dakika',
            latitude: 35.1755,
            longitude: 33.3620,
          },
          {
            id: 'stop-lef-5',
            order: 5,
            type: 'activity',
            name: 'Lokmacı Dükkanları',
            description: 'Geleneksel Kıbrıs tatlısı lokma tadımı',
            timeOfDay: 'afternoon',
            duration: '30 dakika',
            latitude: 35.1745,
            longitude: 33.3630,
            tips: 'Sıcak lokma en lezzetlisidir',
          },
          {
            id: 'stop-lef-6',
            order: 6,
            type: 'restaurant',
            name: 'Dereboyu Caddesi',
            description: 'Modern restoranlar ve akşam yemeği seçenekleri',
            timeOfDay: 'evening',
            duration: '2 saat',
            latitude: 35.1890,
            longitude: 33.3580,
          },
        ],
      },
    ],
  },
  {
    id: 'route-3',
    slug: 'karpaz-doga-kacamagi',
    title: '2 Günde Karpaz Doğa Kaçamağı',
    subtitle: 'El değmemiş doğanın kalbine yolculuk',
    theme: 'nature',
    baseLocation: 'Karpaz',
    region: 'Kuzey Kıbrıs',
    durationDays: 2,
    durationLabel: 'Hafta Sonu',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    tags: ['Doğa', 'Karpaz', 'Plaj', 'Yaban Hayatı'],
    highlighted: true,
    difficulty: 'moderate',
    bestSeason: 'Nisan - Ekim',
    totalStops: 8,
    itinerary: [
      {
        dayIndex: 1,
        title: 'Karpaz\'a Yolculuk',
        description: 'Yarımadanın batı kıyıları',
        stops: [
          {
            id: 'stop-kar-1',
            order: 1,
            type: 'viewpoint',
            name: 'Kantara Kalesi',
            description: 'Karpaz yarımadasına giriş ve panoramik manzara',
            timeOfDay: 'morning',
            duration: '1.5 saat',
            latitude: 35.4050,
            longitude: 33.9220,
            tips: 'Fotoğraf makinenizi unutmayın',
          },
          {
            id: 'stop-kar-2',
            order: 2,
            type: 'activity',
            name: 'Karpaz Eşekleri',
            description: 'Yabani eşeklerle tanışma ve fotoğraf',
            timeOfDay: 'noon',
            duration: '1 saat',
            latitude: 35.5500,
            longitude: 34.3500,
            image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
            tips: 'Eşeklere yiyecek vermek yasaktır',
          },
          {
            id: 'stop-kar-3',
            order: 3,
            type: 'beach',
            name: 'Altın Kum Plajı',
            description: 'KKTC\'nin en güzel plajlarından biri',
            timeOfDay: 'afternoon',
            duration: '3 saat',
            latitude: 35.6200,
            longitude: 34.5100,
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
            tips: 'Deniz ayakkabısı getirin, kayalık bölgeler var',
          },
          {
            id: 'stop-kar-4',
            order: 4,
            type: 'poi',
            name: 'Dipkarpaz Köyü',
            description: 'Gecelik konaklama ve yerel akşam yemeği',
            timeOfDay: 'evening',
            duration: 'Gece',
            latitude: 35.6050,
            longitude: 34.3800,
          },
        ],
      },
      {
        dayIndex: 2,
        title: 'Yarımadanın Ucu',
        description: 'Apostolos Andreas ve gizli koylar',
        stops: [
          {
            id: 'stop-kar-5',
            order: 1,
            type: 'poi',
            name: 'Apostolos Andreas Manastırı',
            description: 'Yarımadanın en ucundaki tarihi manastır',
            timeOfDay: 'morning',
            duration: '1.5 saat',
            latitude: 35.6700,
            longitude: 34.5800,
            tips: 'Sabah erken gidin, daha sakin olur',
          },
          {
            id: 'stop-kar-6',
            order: 2,
            type: 'viewpoint',
            name: 'Zafer Burnu',
            description: 'Kıbrıs\'ın en doğu noktası',
            timeOfDay: 'morning',
            duration: '30 dakika',
            latitude: 35.6750,
            longitude: 34.5900,
          },
          {
            id: 'stop-kar-7',
            order: 3,
            type: 'beach',
            name: 'Kaplıca Plajı',
            description: 'Sakin ve doğal plaj deneyimi',
            timeOfDay: 'noon',
            duration: '2 saat',
            latitude: 35.5800,
            longitude: 34.2500,
          },
          {
            id: 'stop-kar-8',
            order: 4,
            type: 'restaurant',
            name: 'Yenirenköy',
            description: 'Taze balık ve deniz ürünleri ile öğle yemeği',
            timeOfDay: 'afternoon',
            duration: '1.5 saat',
            latitude: 35.5400,
            longitude: 34.1800,
            tips: 'Günün balığını sorun',
          },
        ],
      },
    ],
  },
  {
    id: 'route-4',
    slug: 'gazimagusa-kultur-turu',
    title: 'Gazimağusa Kültür Rotası',
    subtitle: 'Ortaçağ\'dan günümüze uzanan yolculuk',
    theme: 'culture',
    baseLocation: 'Gazimağusa',
    region: 'Kuzey Kıbrıs',
    durationDays: 1,
    durationLabel: 'Tam Gün',
    coverImage: 'https://images.unsplash.com/photo-1553913861-c0a9e9d5c5e9?w=800&h=600&fit=crop',
    tags: ['Kültür', 'Gazimağusa', 'Tarihi', 'Mimari'],
    highlighted: false,
    difficulty: 'easy',
    bestSeason: 'Tüm Yıl',
    totalStops: 5,
    itinerary: [
      {
        dayIndex: 1,
        title: 'Gazimağusa Keşfi',
        description: 'Suriçi ve tarihi yapılar',
        stops: [
          {
            id: 'stop-gaz-1',
            order: 1,
            type: 'poi',
            name: 'Gazimağusa Surları',
            description: 'Venedik döneminden kalma etkileyici surlar',
            timeOfDay: 'morning',
            duration: '1.5 saat',
            latitude: 35.1250,
            longitude: 33.9410,
            tips: 'Othello Kalesi\'ni mutlaka görün',
          },
          {
            id: 'stop-gaz-2',
            order: 2,
            type: 'tour',
            name: 'Lala Mustafa Paşa Camii',
            description: 'Gotik mimari örneği, eski St. Nicholas Katedrali',
            timeOfDay: 'morning',
            duration: '1 saat',
            latitude: 35.1245,
            longitude: 33.9405,
            image: 'https://images.unsplash.com/photo-1553913861-c0a9e9d5c5e9?w=400&h=300&fit=crop',
          },
          {
            id: 'stop-gaz-3',
            order: 3,
            type: 'restaurant',
            name: 'Suriçi Restoranları',
            description: 'Tarihi atmosferde öğle yemeği',
            timeOfDay: 'noon',
            duration: '1.5 saat',
            latitude: 35.1248,
            longitude: 33.9400,
          },
          {
            id: 'stop-gaz-4',
            order: 4,
            type: 'poi',
            name: 'Namık Kemal Zindanı',
            description: 'Ünlü şairin hapsedildiği tarihi mekan',
            timeOfDay: 'afternoon',
            duration: '45 dakika',
            latitude: 35.1252,
            longitude: 33.9408,
          },
          {
            id: 'stop-gaz-5',
            order: 5,
            type: 'beach',
            name: 'Glapsides Plajı',
            description: 'Gün batımı için sahil keyfi',
            timeOfDay: 'evening',
            duration: '2 saat',
            latitude: 35.1180,
            longitude: 33.9650,
          },
        ],
      },
    ],
  },
  {
    id: 'route-5',
    slug: 'besparmak-macera-rotasi',
    title: 'Beşparmak Dağları Macera',
    subtitle: 'Doğa yürüyüşü ve keşif rotası',
    theme: 'adventure',
    baseLocation: 'Girne',
    region: 'Kuzey Kıbrıs',
    durationDays: 1,
    durationLabel: 'Tam Gün',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop',
    tags: ['Macera', 'Doğa Yürüyüşü', 'Dağ', 'Aktif'],
    highlighted: false,
    difficulty: 'challenging',
    bestSeason: 'Mart - Mayıs, Eylül - Kasım',
    totalStops: 4,
    itinerary: [
      {
        dayIndex: 1,
        title: 'Dağ Macerası',
        description: 'Beşparmak Dağları\'nda tırmanış ve keşif',
        stops: [
          {
            id: 'stop-bes-1',
            order: 1,
            type: 'activity',
            name: 'Alevkayası Doğa Parkuru',
            description: 'Sabah yürüyüşü ve kuş gözlemi',
            timeOfDay: 'morning',
            duration: '2 saat',
            latitude: 35.2950,
            longitude: 33.4200,
            tips: 'Bol su ve atıştırmalık getirin',
          },
          {
            id: 'stop-bes-2',
            order: 2,
            type: 'tour',
            name: 'St. Hilarion Kalesi',
            description: 'Masalsı kaleye tırmanış',
            timeOfDay: 'noon',
            duration: '2.5 saat',
            latitude: 35.3115,
            longitude: 33.2815,
            image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=300&fit=crop',
            tips: 'En üst kata çıkmak için iyi kondisyon gerekli',
          },
          {
            id: 'stop-bes-3',
            order: 3,
            type: 'viewpoint',
            name: 'Beşparmak Zirvesi',
            description: 'Panoramik manzara noktası',
            timeOfDay: 'afternoon',
            duration: '1 saat',
            latitude: 35.3050,
            longitude: 33.2900,
          },
          {
            id: 'stop-bes-4',
            order: 4,
            type: 'restaurant',
            name: 'Karaman Köyü',
            description: 'Dağ köyünde geleneksel akşam yemeği',
            timeOfDay: 'evening',
            duration: '1.5 saat',
            latitude: 35.3200,
            longitude: 33.3100,
            tips: 'Köy kahvaltısı için de uğrayabilirsiniz',
          },
        ],
      },
    ],
  },
];

/**
 * Get theme display name in Turkish
 */
export const getThemeDisplayName = (theme: string): string => {
  const themeNames: Record<string, string> = {
    history: 'Tarihi',
    food: 'Yeme-İçme',
    nature: 'Doğa',
    beach: 'Plaj',
    culture: 'Kültür',
    adventure: 'Macera',
  };
  return themeNames[theme] || theme;
};

/**
 * Get theme icon name (Ionicons)
 */
export const getThemeIcon = (theme: string): string => {
  const themeIcons: Record<string, string> = {
    history: 'library-outline',
    food: 'restaurant-outline',
    nature: 'leaf-outline',
    beach: 'sunny-outline',
    culture: 'color-palette-outline',
    adventure: 'compass-outline',
  };
  return themeIcons[theme] || 'map-outline';
};

/**
 * Get stop type icon name (Ionicons)
 */
export const getStopTypeIcon = (type: string): string => {
  const typeIcons: Record<string, string> = {
    tour: 'location',
    poi: 'pin',
    restaurant: 'restaurant',
    cafe: 'cafe',
    activity: 'bicycle',
    viewpoint: 'eye',
    beach: 'sunny',
  };
  return typeIcons[type] || 'ellipse';
};

/**
 * Get time of day display name
 */
export const getTimeOfDayLabel = (timeOfDay: string): string => {
  const key = `explore.timeOfDay.${timeOfDay}`;
  const translated = i18n.t(key);
  return translated && translated !== key ? translated : timeOfDay;
};

/**
 * Get difficulty display name and color
 */
export const getDifficultyInfo = (difficulty?: string): { label: string; color: string } => {
  const info: Record<string, { label: string; color: string }> = {
    easy: { label: i18n.t('explore.difficulties.easy'), color: '#22C55E' },
    moderate: { label: i18n.t('explore.difficulties.moderate'), color: '#F59E0B' },
    challenging: { label: i18n.t('explore.difficulties.challenging'), color: '#EF4444' },
  };

  return info[difficulty || ''] || { label: difficulty || '', color: '#6B7280' };
};
